name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push api-gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
      
      - name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: ./auth-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth:latest
        
      - name: Build and push product
        uses: docker/build-push-action@v2
        with:
          context: ./product-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product:latest
      
      - name: Build and push order
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order:latest
